import React, { useState, useEffect, useRef } from 'react';
import { transliterate } from 'transliteration';
import '../App.css';

const englishTexts = [
    "The Indian economy has undergone significant structural changes since Independence, moving from a predominantly agrarian system toward a diversified economy supported by agriculture, manufacturing, and services. In the early decades, the government emphasized planned development, public-sector enterprises, infrastructure, and self-reliance. The economic reforms introduced in 1991 marked an important turning point by encouraging liberalization, privatization, and globalization. Since then, India has witnessed substantial growth in sectors such as information technology, telecommunications, banking, pharmaceuticals, automobiles, and digital services. The expansion of the middle class has increased domestic consumption, while improved connectivity has created new opportunities for businesses in both urban and rural areas. Agriculture continues to employ a large share of the population and remains important for food security, rural income, and social stability. At the same time, manufacturing initiatives such as MAKE IN INDIA have sought to increase industrial production, attract investment, and strengthen supply chains. The growth of digital payments has also transformed economic activity. Systems such as UPI have made financial transactions faster and more accessible, particularly for small businesses and individual consumers. However, several challenges remain. Employment generation, income inequality, skill development, inflation, regional disparities, and access to quality education require sustained attention. India's young population can become a major economic advantage if adequate opportunities for training and productive employment are created. Infrastructure investment in roads, railways, ports, renewable energy, and communication networks is equally important. The government, private sector, financial institutions, and citizens all have roles in supporting inclusive development. A strong economy should not be measured only by GDP growth; it should also be assessed through improvements in productivity, living standards, employment, education, health, and access to essential services. Sustainable economic progress therefore requires a balanced approach that combines innovation with social responsibility. If India can improve human capital, encourage entrepreneurship, strengthen institutions, and maintain macroeconomic stability, its economic transformation can provide wider opportunities for future generations.",
"Technology has become one of the most influential forces shaping modern society. During the last few decades, rapid developments in computers, telecommunications, artificial intelligence, biotechnology, and digital networks have changed the way people work, communicate, learn, and conduct business. The spread of smartphones and affordable internet services has connected millions of people with information and services that were previously difficult to access. In India, digital technology has supported banking, education, public administration, transportation, healthcare, and commerce. Online platforms enable citizens to obtain documents, make payments, apply for services, and communicate with institutions without travelling long distances. Artificial Intelligence, commonly known as AI, is increasingly being used for data analysis, language processing, medical research, customer support, and industrial automation. However, technological progress also creates important responsibilities. The collection and processing of large quantities of personal data raise questions about privacy and cybersecurity. Automated systems may also change the nature of employment by reducing demand for certain repetitive tasks while creating new occupations requiring advanced skills. Therefore, education systems must adapt to changing requirements and provide students with digital literacy, analytical ability, creativity, and practical knowledge. Technology should remain a means of improving human welfare rather than becoming an uncontrolled objective in itself. Rural areas require particular attention because unequal access to devices, reliable electricity, and high-speed connectivity can create a digital divide. Governments and private organizations can help by expanding infrastructure and providing affordable services. Cybersecurity awareness is equally necessary because online fraud, identity theft, and malicious software can cause serious financial and social harm. Responsible innovation should include transparency, accountability, accessibility, and respect for human rights. The successful use of technology ultimately depends not only on advanced machines but also on informed citizens, effective institutions, ethical standards, and appropriate regulation. A technologically capable society is one that uses innovation to improve productivity and public welfare while ensuring that its benefits are distributed as widely as possible.",
"Environmental protection has become an essential requirement for sustainable development because natural resources support agriculture, industry, public health, and human survival. Rapid urbanization, industrial expansion, population growth, and increased consumption have placed considerable pressure on forests, rivers, groundwater, soil, and biodiversity. Air pollution in major cities is influenced by several factors, including vehicular emissions, industrial activity, construction dust, and the burning of fuels and waste. Water pollution can result from untreated sewage, industrial discharge, agricultural chemicals, and improper disposal of solid waste. Climate change has added another dimension to these challenges by increasing the frequency or intensity of certain extreme weather events and affecting ecosystems and livelihoods. India, with its diverse geography, is particularly dependent on effective environmental management. The Himalayan region, coastal areas, forests, wetlands, and agricultural plains each face different risks. Renewable energy sources such as solar and wind power can reduce dependence on fossil fuels and contribute to cleaner energy production. Energy efficiency is also important because saving electricity and fuel can reduce both costs and environmental pressure. Individuals can contribute by reducing unnecessary consumption, avoiding single-use plastic, conserving water, using public transportation where practical, and separating household waste. Industries must adopt cleaner production methods and comply with environmental standards. Local governments have an important responsibility in waste management, drainage, sanitation, and urban planning. Environmental education should begin at an early age so that conservation becomes a practical habit rather than merely a theoretical concept. Economic development and environmental protection need not be treated as completely opposing objectives. Proper planning can encourage green industries, sustainable agriculture, efficient public transport, and responsible use of natural resources. The principle of sustainable development requires present generations to meet their needs without seriously reducing the ability of future generations to meet theirs. Protecting the environment is therefore not only a scientific or administrative task; it is also a social responsibility involving governments, businesses, communities, educational institutions, and individual citizens.",
"The history of India's freedom movement represents a long and complex struggle involving political leaders, social reformers, workers, farmers, students, writers, and ordinary citizens. The revolt of 1857 was an important early challenge to British authority, although its causes and character were diverse across different regions. Later, the formation of the Indian National Congress in 1885 provided an organized political platform for expressing Indian demands. During the early phase, leaders emphasized constitutional methods, administrative reform, and greater Indian participation in government. The partition of Bengal in 1905 generated widespread opposition and contributed to the growth of the Swadeshi and Boycott movements. In the following decades, the national movement became broader and more closely connected with mass participation. Mahatma Gandhi introduced methods of non-violent resistance and emphasized Satyagraha, self-discipline, and public mobilization. The Non-Cooperation Movement of 1920-22 encouraged people to withdraw support from colonial institutions. The Civil Disobedience Movement, including the historic Salt March of 1930, challenged laws considered unjust and demonstrated the power of organized peaceful protest. The Quit India Movement of 1942 called for an immediate end to British rule and led to widespread arrests and demonstrations. Alongside these movements, revolutionary groups and leaders followed different methods and contributed to the broader struggle. Subhas Chandra Bose and the Indian National Army became important symbols of militant resistance and national determination. Women also played significant roles in protests, underground activities, social work, and political mobilization. The independence movement was not limited to a single ideology or method; it contained different viewpoints regarding constitutional reform, social equality, economic development, and political strategy. India achieved independence on 15 AUGUST 1947, but partition accompanied the transfer of power and caused enormous human suffering and displacement. The making of the Constitution subsequently established a democratic framework based on justice, liberty, equality, and fraternity. Studying this period helps citizens understand both the sacrifices associated with independence and the responsibilities required to preserve democratic institutions.",
"Education is one of the most important instruments for individual development and national progress. It provides knowledge, develops reasoning ability, improves communication, and helps people participate effectively in social and economic life. A strong education system should not focus only on examination results; it should also develop discipline, creativity, scientific temper, ethical awareness, and practical skills. India has made substantial progress in expanding access to schools and higher educational institutions, but challenges related to quality, infrastructure, teacher availability, and regional inequality continue to require attention. Digital learning has created new possibilities by allowing students to access lectures, books, practice materials, and educational platforms from different locations. However, online education cannot completely replace the value of trained teachers, classroom interaction, libraries, laboratories, and extracurricular activities. The digital divide remains a concern because students from economically weaker families may lack suitable devices or reliable internet connections. Vocational education and skill development are also increasingly important in an economy where technology and workplace requirements are changing rapidly. Young people need opportunities to develop abilities that correspond to actual employment needs while retaining the flexibility to learn throughout their careers. Higher education should encourage research, innovation, critical thinking, and collaboration with industry and public institutions. At the school level, foundational literacy and numeracy are particularly important because weaknesses at an early stage can affect later learning. Education should also promote constitutional values, environmental awareness, gender equality, respect for diversity, and responsible citizenship. Parents, teachers, administrators, and communities all contribute to creating a supportive learning environment. Public investment is necessary for improving schools, training teachers, developing laboratories, and providing scholarships to deserving students. At the same time, educational institutions must maintain accountability and academic standards. The ultimate purpose of education is not merely to produce candidates for examinations. It is to prepare individuals who can understand problems, evaluate evidence, make responsible decisions, and contribute constructively to society. A country that invests in the education of its young population strengthens its capacity for innovation, economic development, social stability, and democratic participation.",
"Urbanization is an important feature of India's social and economic transformation. Cities provide employment opportunities, educational institutions, hospitals, markets, transportation networks, and cultural facilities, attracting people from rural and smaller urban areas. The growth of cities can contribute to productivity because businesses, workers, consumers, and infrastructure are located relatively close to one another. However, rapid and poorly planned urbanization can also create serious difficulties. Traffic congestion, air pollution, inadequate housing, water shortages, flooding, waste accumulation, and pressure on public services are common concerns in rapidly expanding urban areas. Effective urban planning must therefore anticipate population growth rather than respond only after problems become severe. Public transportation is a key component of sustainable urban development. Metro rail, buses, suburban trains, cycling infrastructure, and pedestrian-friendly streets can reduce dependence on private vehicles and improve mobility. Affordable housing is equally important because workers in essential occupations need to live within reasonable distance of employment centres. Urban local bodies require adequate financial resources, technical capacity, and administrative autonomy to provide reliable services. Waste management should include segregation, collection, recycling, treatment, and safe disposal. Water security requires conservation, efficient distribution, rainwater harvesting, wastewater treatment, and protection of local water bodies. Green spaces such as parks and urban forests can improve environmental quality and provide recreational benefits. Technology can assist city administration through digital mapping, traffic monitoring, online service delivery, and data-based planning, but technological systems must be supported by sound institutions and trained personnel. Climate resilience should also become an important part of urban planning because extreme rainfall, heat waves, and other environmental stresses can disrupt infrastructure and public life. Citizens have a role in maintaining public spaces, following traffic rules, conserving resources, and cooperating with local authorities. The objective of urban development should be to create cities that are economically productive, environmentally responsible, accessible, and inclusive. Good planning requires coordination among national and state governments, municipal bodies, private developers, experts, and local communities. When urban growth is managed carefully, cities can become centres of innovation and opportunity without imposing unsustainable costs on future generations.",
"Agriculture continues to play a central role in India's economy, society, and food security. Millions of rural households depend directly or indirectly on farming and related activities such as dairy, fisheries, poultry, and food processing. Indian agriculture is diverse because farmers operate under different climatic conditions, soil types, irrigation facilities, and market arrangements. Rice, wheat, pulses, oilseeds, cotton, sugarcane, fruits, and vegetables are among the major crops cultivated in different regions. The Green Revolution significantly increased the production of wheat and rice in several parts of the country and helped strengthen national food security. However, agriculture still faces challenges including small and fragmented landholdings, irregular rainfall, groundwater depletion, rising input costs, storage limitations, and market fluctuations. Climate change may further increase uncertainty by affecting temperature, rainfall patterns, and the frequency of extreme weather events. Irrigation expansion and efficient water management can reduce dependence on unpredictable rainfall. Drip irrigation, sprinkler systems, soil testing, crop diversification, and improved seeds can help farmers use resources more efficiently. Post-harvest infrastructure is equally important because inadequate storage and transportation can result in substantial losses of perishable commodities. Food processing industries can create additional value and employment while connecting farmers with wider markets. Agricultural research and extension services should ensure that scientific knowledge reaches farmers in understandable and practical forms. Digital platforms can provide information about weather, prices, crop management, and government schemes, although access and digital literacy must also be considered. Farmer organizations and cooperatives can improve bargaining capacity and facilitate collective purchasing, storage, processing, and marketing. Sustainable agriculture requires careful management of soil fertility, water resources, biodiversity, and chemical inputs. Rural development must also provide opportunities outside farming because agriculture alone cannot absorb every new worker entering the labour market. Education, healthcare, roads, electricity, internet connectivity, and non-farm employment are therefore closely connected with agricultural prosperity. A resilient agricultural system should combine productivity with sustainability and ensure that farmers have reasonable opportunities to earn stable incomes. Strengthening the rural economy is essential for balanced national development and for improving the quality of life of India's large rural population.",
"Public health is a fundamental component of social welfare and economic development. A healthy population is better able to learn, work, and participate in community life, while widespread illness can reduce household income and place pressure on public institutions. Health systems therefore require a combination of preventive care, primary healthcare, hospitals, trained professionals, medicines, diagnostic facilities, and emergency services. Preventive measures such as vaccination, sanitation, clean drinking water, nutrition, physical activity, and health education can reduce the burden of many diseases. Primary healthcare is especially important because early diagnosis and treatment can prevent minor conditions from becoming serious. Rural and remote communities may face difficulties in accessing specialists and advanced medical facilities, making local health centres and trained health workers essential. India has expanded health infrastructure over the years, but differences in access and quality remain across regions and income groups. Digital health services, telemedicine, electronic records, and mobile applications can improve access when supported by reliable connectivity and appropriate safeguards for personal information. Public awareness is also necessary because misinformation can influence health-related decisions and delay appropriate treatment. Hospitals must maintain standards of hygiene, patient safety, emergency preparedness, and professional ethics. Mental well-being, nutrition, maternal health, child health, and care for older persons should form part of a comprehensive health strategy. Health expenditure can become a serious financial burden for families, so effective insurance and public support mechanisms can reduce the risk of households falling into poverty because of medical costs. Environmental conditions also influence health. Air pollution, contaminated water, poor sanitation, and unsafe working conditions can contribute to disease and reduced productivity. Collaboration among governments, medical institutions, researchers, community organizations, and citizens is therefore essential. Individuals can contribute by following preventive advice, maintaining healthy habits, seeking qualified medical care, and avoiding the spread of false information. A strong public health system should be accessible, affordable, accountable, and prepared for emergencies. Investment in health is not merely an expenditure on welfare; it is also an investment in human capital, productivity, social stability, and long-term national development.",
"Infrastructure is a foundation of economic activity because roads, railways, ports, airports, electricity networks, communication systems, and water facilities connect people and markets. Efficient infrastructure reduces transportation costs, improves access to services, encourages investment, and supports the movement of goods and workers. India has expanded its physical and digital infrastructure considerably, but the country's large population and geographical diversity create continuing requirements for new investment and maintenance. High-quality roads can connect villages with markets, schools, hospitals, and employment centres. Railways provide large-scale passenger and freight transportation and can reduce pressure on road networks. Ports are important for international trade, while airports support tourism, business travel, and regional connectivity. Reliable electricity is essential for households, agriculture, manufacturing, hospitals, and digital services. The expansion of renewable energy has created opportunities for diversifying the power sector, although energy storage and transmission infrastructure require continued development. Digital infrastructure has become equally significant. Broadband networks, mobile connectivity, data centres, and secure digital platforms support financial services, education, government administration, and modern business. Infrastructure projects often involve large public investments and long planning periods, making transparency and careful financial management essential. Environmental considerations must also be incorporated into project design so that economic benefits do not create avoidable ecological damage. Land acquisition, rehabilitation, and community participation require fair and transparent procedures. Maintenance is as important as construction because poorly maintained infrastructure can reduce efficiency and increase long-term costs. Public-private partnerships can bring additional capital and technical expertise, but contracts must clearly define responsibilities, performance standards, and accountability. Infrastructure should also be designed for resilience against floods, earthquakes, cyclones, heat, and other hazards relevant to each region. Balanced development requires attention not only to major metropolitan centres but also to smaller towns, villages, border areas, and economically weaker regions. Good infrastructure ultimately improves the daily lives of citizens by saving time, reducing costs, expanding opportunities, and connecting communities. Long-term national planning should therefore treat infrastructure as an integrated system rather than as a collection of unrelated projects. Sustainable investment, effective regulation, skilled personnel, and regular maintenance are necessary to ensure that infrastructure continues to serve public needs for decades.",
"Scientific research and innovation have played a major role in transforming modern India. From space exploration and nuclear science to pharmaceuticals, agriculture, information technology, and renewable energy, scientific institutions have contributed to national development in many fields. India's space programme demonstrates how long-term investment in research can produce both strategic and civilian benefits. Missions involving satellites, communication, weather observation, navigation, and planetary exploration have strengthened scientific capability and provided practical services. Agricultural research has contributed to improved crop varieties, pest management, irrigation practices, and food production. Medical research has supported the development of diagnostics, vaccines, medicines, and public health programmes. In recent years, artificial intelligence, robotics, biotechnology, quantum technologies, and advanced materials have opened new areas of research and industrial opportunity. Scientific progress requires more than laboratories and equipment. It depends on skilled researchers, strong educational institutions, stable funding, international cooperation, and an environment in which curiosity and critical thinking are encouraged. Young students should have opportunities to conduct experiments, participate in science exhibitions, and understand how evidence is used to test ideas. Public understanding of science is equally important because citizens regularly encounter questions involving health, climate, technology, and public policy that require the ability to distinguish reliable evidence from misinformation. Research institutions should maintain high standards of integrity, transparency, and reproducibility. Collaboration between universities, government laboratories, startups, and established industries can help convert scientific discoveries into useful products and services. At the same time, ethical considerations must remain central, particularly in areas such as genetic engineering, artificial intelligence, data analysis, and medical experimentation. Scientific innovation should aim to improve human welfare while respecting safety, privacy, and environmental limits. Investment in research may not always produce immediate results, but long-term scientific capacity strengthens national resilience and economic competitiveness. India has a large pool of young people and a growing network of educational institutions, creating substantial potential for future research. To realize that potential, the country needs sustained support for basic science as well as applied research, better laboratory infrastructure, international collaboration, and stronger links between education and innovation. A scientifically informed society is better prepared to solve complex problems and make responsible decisions in an increasingly technological world."
];

const hindiTexts = [
    "स्वतंत्र भारत के विकास में लोकतांत्रिक संस्थाओं की महत्वपूर्ण भूमिका रही है। भारतीय संविधान ने देश को एक संप्रभु, समाजवादी, पंथनिरपेक्ष, लोकतांत्रिक गणराज्य के रूप में स्थापित किया और नागरिकों को न्याय, स्वतंत्रता, समानता तथा बंधुता के मूल्यों का आश्वासन दिया। लोकतंत्र केवल चुनाव कराने की व्यवस्था नहीं है, बल्कि यह नागरिकों की भागीदारी, कानून का शासन, उत्तरदायी शासन और संस्थागत संतुलन पर आधारित प्रणाली है। भारत में प्रत्येक 5 वर्ष के अंतराल पर लोकसभा के चुनाव आयोजित किए जाते हैं, जबकि विभिन्न राज्यों में विधानसभाओं के चुनाव अलग-अलग समय पर होते हैं। स्वतंत्र और निष्पक्ष चुनाव के लिए निर्वाचन आयोग की भूमिका अत्यंत महत्वपूर्ण है। संसद कानून बनाने, सरकार के कार्यों पर चर्चा करने और सार्वजनिक नीतियों की समीक्षा करने का प्रमुख मंच है। इसी प्रकार न्यायपालिका संविधान और कानूनों की व्याख्या करते हुए नागरिक अधिकारों की रक्षा में महत्वपूर्ण योगदान देती है। संघीय व्यवस्था के अंतर्गत केंद्र और राज्य सरकारों के बीच शक्तियों का विभाजन किया गया है। स्थानीय स्वशासन की संस्थाएँ, जैसे नगर निकाय और ग्राम पंचायतें, नागरिकों की दैनिक आवश्यकताओं से जुड़े कार्यों का संचालन करती हैं। लोकतांत्रिक व्यवस्था की सफलता के लिए जागरूक नागरिक आवश्यक हैं। नागरिकों को अपने अधिकारों के साथ-साथ कर्तव्यों की भी जानकारी होनी चाहिए। मतदान करना, कानूनों का पालन करना, सार्वजनिक संपत्ति की रक्षा करना और सामाजिक सद्भाव बनाए रखना जिम्मेदार नागरिकता के महत्वपूर्ण तत्व हैं। मीडिया भी लोकतंत्र में सूचना उपलब्ध कराने और सार्वजनिक मुद्दों पर चर्चा को बढ़ावा देने का माध्यम है, लेकिन सूचना प्राप्त करते समय तथ्य और अफवाह के बीच अंतर करना आवश्यक है। डिजिटल युग में सोशल मीडिया ने संवाद को तेज किया है, परंतु गलत सूचना के प्रसार की संभावना भी बढ़ी है। इसलिए नागरिकों में तथ्य-जांच और आलोचनात्मक सोच की क्षमता विकसित करना आवश्यक है। मजबूत लोकतंत्र वही है जिसमें संस्थाएँ संविधान के अनुरूप कार्य करें, नागरिक जागरूक रहें और असहमति को शांतिपूर्ण तथा वैधानिक तरीकों से व्यक्त किया जाए। लोकतांत्रिक मूल्यों की रक्षा किसी एक संस्था की जिम्मेदारी नहीं, बल्कि पूरे समाज का सामूहिक दायित्व है।",
"भारत में शिक्षा को सामाजिक परिवर्तन और राष्ट्रीय प्रगति का आधार माना जाता है। शिक्षा व्यक्ति को ज्ञान प्रदान करने के साथ-साथ उसके विचारों, व्यवहार और निर्णय लेने की क्षमता को विकसित करती है। एक प्रभावी शिक्षा व्यवस्था का उद्देश्य केवल परीक्षा में अच्छे अंक प्राप्त करना नहीं होना चाहिए, बल्कि विद्यार्थियों में तार्किक सोच, अनुशासन, रचनात्मकता, वैज्ञानिक दृष्टिकोण और सामाजिक उत्तरदायित्व की भावना भी विकसित करनी चाहिए। प्राथमिक स्तर पर भाषा और गणित की मजबूत नींव आगे की शिक्षा के लिए अत्यंत आवश्यक होती है। यदि किसी बच्चे को प्रारंभिक कक्षाओं में पढ़ने, लिखने और मूलभूत गणना की पर्याप्त समझ नहीं मिलती, तो आगे की पढ़ाई में कठिनाई उत्पन्न हो सकती है। भारत में विद्यालयों और उच्च शिक्षण संस्थानों की संख्या में वृद्धि हुई है, फिर भी गुणवत्तापूर्ण शिक्षा तक समान पहुँच एक महत्वपूर्ण चुनौती बनी हुई है। ग्रामीण क्षेत्रों में विद्यालयी भवन, पुस्तकालय, प्रयोगशाला, इंटरनेट सुविधा और प्रशिक्षित शिक्षकों की उपलब्धता पर विशेष ध्यान देने की आवश्यकता है। डिजिटल शिक्षा ने विद्यार्थियों को ऑनलाइन पाठ्य सामग्री, व्याख्यान और अभ्यास के नए अवसर दिए हैं। परंतु प्रत्येक विद्यार्थी के पास स्मार्टफोन, कंप्यूटर या विश्वसनीय इंटरनेट उपलब्ध हो, यह आवश्यक नहीं है। इस कारण डिजिटल विभाजन को कम करना भी शिक्षा नीति का महत्वपूर्ण उद्देश्य होना चाहिए। व्यावसायिक और कौशल आधारित शिक्षा का महत्व भी बढ़ रहा है, क्योंकि आधुनिक अर्थव्यवस्था में तकनीकी दक्षता और व्यावहारिक ज्ञान की मांग निरंतर बदल रही है। शिक्षक शिक्षा व्यवस्था के केंद्र में होते हैं और उनके प्रशिक्षण, सम्मान तथा कार्य परिस्थितियों में सुधार आवश्यक है। शिक्षा में नैतिक मूल्यों, संविधान की भावना, पर्यावरण संरक्षण, लैंगिक समानता और सामाजिक समरसता को भी उचित स्थान मिलना चाहिए। उच्च शिक्षा में अनुसंधान और नवाचार को प्रोत्साहन देने से देश की वैज्ञानिक तथा आर्थिक क्षमता बढ़ सकती है। छात्रवृत्ति, पुस्तक सहायता और अन्य वित्तीय उपाय आर्थिक रूप से कमजोर विद्यार्थियों को आगे बढ़ने में सहायता कर सकते हैं। शिक्षा में निवेश का लाभ केवल विद्यार्थी को नहीं, बल्कि पूरे समाज और राष्ट्र को मिलता है। ज्ञानवान, कुशल और जिम्मेदार नागरिक किसी भी देश की सबसे महत्वपूर्ण संपत्ति होते हैं।",
"पर्यावरण संरक्षण वर्तमान समय की प्रमुख आवश्यकताओं में से एक है। पृथ्वी पर उपलब्ध जल, वन, मिट्टी, खनिज और जैव विविधता मानव जीवन तथा आर्थिक गतिविधियों के लिए अत्यंत महत्वपूर्ण हैं। जनसंख्या वृद्धि, औद्योगीकरण, शहरीकरण और प्राकृतिक संसाधनों के अत्यधिक उपयोग के कारण पर्यावरण पर दबाव बढ़ा है। वायु प्रदूषण का प्रभाव मानव स्वास्थ्य, कृषि और पारिस्थितिक तंत्र पर पड़ सकता है। जल प्रदूषण के प्रमुख कारणों में घरेलू सीवेज, औद्योगिक अपशिष्ट, कृषि रसायन और ठोस कचरे का अनुचित निपटान शामिल हैं। वन क्षेत्र जैव विविधता की रक्षा करने के साथ-साथ जलवायु को संतुलित रखने, मिट्टी के कटाव को कम करने और अनेक समुदायों की आजीविका में सहायता करते हैं। इसलिए वनों का संरक्षण केवल पर्यावरणीय विषय नहीं, बल्कि आर्थिक और सामाजिक आवश्यकता भी है। जल संरक्षण के लिए वर्षा जल संचयन, तालाबों और झीलों का पुनर्जीवन, भूजल का संतुलित उपयोग तथा सिंचाई की दक्ष तकनीकों को अपनाना आवश्यक है। ऊर्जा क्षेत्र में सौर और पवन ऊर्जा जैसे नवीकरणीय स्रोतों का उपयोग बढ़ाने से जीवाश्म ईंधनों पर निर्भरता कम करने में सहायता मिल सकती है। घरेलू स्तर पर नागरिक बिजली और पानी की बचत, कचरे का पृथक्करण, पुनर्चक्रण और प्लास्टिक के अनावश्यक उपयोग में कमी जैसे कदम उठा सकते हैं। उद्योगों को स्वच्छ उत्पादन तकनीक अपनानी चाहिए और निर्धारित पर्यावरणीय मानकों का पालन करना चाहिए। नगर निकायों की जिम्मेदारी है कि वे कचरा संग्रहण, निस्तारण, जल निकासी और स्वच्छता की उचित व्यवस्था करें। विद्यालयों में पर्यावरण शिक्षा को व्यवहारिक गतिविधियों से जोड़ा जाना चाहिए, ताकि विद्यार्थियों में संरक्षण की आदत विकसित हो। जलवायु परिवर्तन ने पर्यावरणीय चुनौतियों को और गंभीर बनाया है तथा कृषि, स्वास्थ्य और तटीय क्षेत्रों पर इसके प्रभावों का अध्ययन आवश्यक है। विकास और पर्यावरण संरक्षण को परस्पर विरोधी मानना उचित नहीं है। सुविचारित योजना के माध्यम से आर्थिक विकास के साथ प्राकृतिक संसाधनों की रक्षा की जा सकती है। वर्तमान पीढ़ी का दायित्व है कि वह प्राकृतिक संपदा का ऐसा उपयोग करे जिससे आने वाली पीढ़ियों के लिए भी पर्याप्त संसाधन उपलब्ध रहें। सतत विकास का यही मूल उद्देश्य है।",
"भारत की कृषि व्यवस्था देश की अर्थव्यवस्था और ग्रामीण समाज का महत्वपूर्ण आधार है। बड़ी संख्या में लोग प्रत्यक्ष या अप्रत्यक्ष रूप से कृषि तथा उससे संबंधित गतिविधियों पर निर्भर हैं। भारत की भौगोलिक और जलवायु विविधता के कारण विभिन्न राज्यों में अलग-अलग प्रकार की फसलें उगाई जाती हैं। गेहूँ, धान, दालें, तिलहन, कपास, गन्ना, फल और सब्जियाँ प्रमुख कृषि उत्पादों में शामिल हैं। हरित क्रांति ने विशेष रूप से गेहूँ और धान के उत्पादन में उल्लेखनीय वृद्धि की तथा देश की खाद्य सुरक्षा को मजबूत करने में योगदान दिया। इसके बावजूद कृषि क्षेत्र के सामने अनेक चुनौतियाँ हैं। छोटे और सीमांत किसानों के पास भूमि का आकार कम होने के कारण आधुनिक तकनीक और मशीनरी का उपयोग कठिन हो सकता है। अनियमित मानसून, भूजल का अत्यधिक दोहन, बढ़ती लागत, भंडारण की कमी और बाजार मूल्यों में उतार-चढ़ाव किसानों की आय को प्रभावित करते हैं। सिंचाई सुविधाओं का विस्तार और जल का कुशल उपयोग कृषि की उत्पादकता बढ़ाने में सहायता कर सकता है। ड्रिप सिंचाई, स्प्रिंकलर, मृदा परीक्षण और उचित फसल चक्र जैसी तकनीकों से संसाधनों का संरक्षण किया जा सकता है। कृषि अनुसंधान से बेहतर बीज, रोग नियंत्रण और मौसम के अनुकूल उत्पादन पद्धतियाँ विकसित की जा सकती हैं। कटाई के बाद भंडारण और परिवहन की पर्याप्त व्यवस्था न होने से फल, सब्जियों और अन्य शीघ्र खराब होने वाली वस्तुओं का नुकसान होता है। खाद्य प्रसंस्करण उद्योग इस समस्या को कम करने के साथ किसानों को अतिरिक्त बाजार उपलब्ध करा सकता है। किसान उत्पादक संगठन और सहकारी संस्थाएँ सामूहिक खरीद, भंडारण और विपणन में उपयोगी भूमिका निभा सकती हैं। डिजिटल तकनीक के माध्यम से किसानों को मौसम, बाजार मूल्य और कृषि संबंधी जानकारी उपलब्ध कराई जा सकती है। हालांकि, डिजिटल सुविधा के साथ प्रशिक्षण और स्थानीय भाषा में जानकारी भी आवश्यक है। टिकाऊ कृषि के लिए मिट्टी की उर्वरता, जल संसाधन और जैव विविधता का संरक्षण जरूरी है। ग्रामीण विकास केवल खेती की उत्पादकता तक सीमित नहीं होना चाहिए। सड़क, बिजली, शिक्षा, स्वास्थ्य, इंटरनेट और गैर-कृषि रोजगार के अवसर ग्रामीण अर्थव्यवस्था को मजबूत करते हैं। किसानों की स्थिति सुधारने के लिए उत्पादन, बाजार, तकनीक और सामाजिक सुरक्षा से संबंधित प्रयासों का समन्वय आवश्यक है। मजबूत ग्रामीण अर्थव्यवस्था देश के संतुलित विकास के लिए अत्यंत महत्वपूर्ण है।",
"भारत में विज्ञान और प्रौद्योगिकी ने राष्ट्रीय विकास के अनेक क्षेत्रों को प्रभावित किया है। अंतरिक्ष अनुसंधान, परमाणु ऊर्जा, सूचना प्रौद्योगिकी, चिकित्सा, कृषि और संचार के क्षेत्र में वैज्ञानिक उपलब्धियों ने देश की क्षमता को मजबूत किया है। भारतीय अंतरिक्ष कार्यक्रम ने उपग्रह प्रक्षेपण, मौसम पूर्वानुमान, दूरसंचार, पृथ्वी अवलोकन और अंतरिक्ष अनुसंधान में महत्वपूर्ण योगदान दिया है। उपग्रहों से प्राप्त जानकारी का उपयोग कृषि, आपदा प्रबंधन, मानचित्रण और संचार सेवाओं में भी किया जाता है। चिकित्सा क्षेत्र में अनुसंधान ने रोगों की पहचान, औषधि विकास, टीकाकरण और उपचार की नई संभावनाएँ विकसित की हैं। कृषि विज्ञान ने उन्नत बीज, सिंचाई तकनीक, मृदा प्रबंधन और कीट नियंत्रण के माध्यम से उत्पादन बढ़ाने में सहायता की है। वर्तमान समय में कृत्रिम बुद्धिमत्ता, जैव प्रौद्योगिकी, रोबोटिक्स, क्वांटम प्रौद्योगिकी और नवीकरणीय ऊर्जा जैसे क्षेत्रों में तेजी से अनुसंधान हो रहा है। विज्ञान की प्रगति के लिए केवल आधुनिक प्रयोगशालाएँ पर्याप्त नहीं हैं। कुशल वैज्ञानिक, प्रशिक्षित तकनीकी कर्मचारी, पर्याप्त वित्तीय सहायता और स्वतंत्र अनुसंधान वातावरण भी आवश्यक हैं। विद्यालय स्तर पर विद्यार्थियों में वैज्ञानिक दृष्टिकोण विकसित किया जाना चाहिए। प्रयोगशाला गतिविधियाँ, विज्ञान प्रदर्शनियाँ और समस्या आधारित अध्ययन विद्यार्थियों को प्रश्न पूछने और प्रमाण के आधार पर निष्कर्ष निकालने के लिए प्रेरित कर सकते हैं। वैज्ञानिक जानकारी के अभाव में अफवाह और भ्रामक सूचना तेजी से फैल सकती है, विशेषकर डिजिटल माध्यमों पर। इसलिए नागरिकों में तथ्य-जांच और तार्किक विश्लेषण की क्षमता विकसित करना महत्वपूर्ण है। कृत्रिम बुद्धिमत्ता और जैव प्रौद्योगिकी जैसी उन्नत तकनीकों के उपयोग में नैतिकता, सुरक्षा और गोपनीयता का ध्यान रखना आवश्यक है। विश्वविद्यालयों, सरकारी अनुसंधान संस्थानों, उद्योगों और स्टार्टअप के बीच सहयोग से वैज्ञानिक खोजों को उपयोगी उत्पादों और सेवाओं में बदला जा सकता है। मूलभूत विज्ञान में निवेश का परिणाम हमेशा तुरंत दिखाई नहीं देता, लेकिन दीर्घकालीन वैज्ञानिक क्षमता राष्ट्र की आत्मनिर्भरता और प्रतिस्पर्धात्मक शक्ति को बढ़ाती है। भारत की युवा आबादी विज्ञान और नवाचार के क्षेत्र में बड़ी संभावना रखती है। इस संभावना को साकार करने के लिए गुणवत्तापूर्ण शिक्षा, अनुसंधान सुविधाओं, वित्तीय सहायता और अंतरराष्ट्रीय सहयोग को निरंतर प्रोत्साहित करना आवश्यक है। वैज्ञानिक सोच एक आधुनिक और जिम्मेदार समाज की आधारशिला है।",
"भारत में डिजिटल प्रौद्योगिकी के विस्तार ने प्रशासन, व्यापार, शिक्षा और वित्तीय सेवाओं के क्षेत्र में महत्वपूर्ण परिवर्तन किए हैं। इंटरनेट और स्मार्टफोन की उपलब्धता बढ़ने से नागरिकों को अनेक सेवाएँ घर बैठे प्राप्त करने की सुविधा मिली है। डिजिटल भुगतान प्रणाली ने छोटे व्यापारियों और सामान्य उपभोक्ताओं के लिए लेन-देन को सरल बनाया है। UPI जैसी प्रणालियों ने बैंक खाते से सीधे भुगतान करने की प्रक्रिया को तेज और सुविधाजनक बनाया है। सरकारी सेवाओं में डिजिटल प्लेटफॉर्म के उपयोग से आवेदन, प्रमाण-पत्र, कर भुगतान और अन्य प्रक्रियाओं में समय की बचत हो सकती है। ग्रामीण क्षेत्रों में इंटरनेट की पहुँच बढ़ने से विद्यार्थियों, किसानों और छोटे उद्यमियों को नई जानकारी प्राप्त करने के अवसर मिले हैं। हालांकि डिजिटल विकास के साथ कुछ चुनौतियाँ भी सामने आई हैं। साइबर अपराध, ऑनलाइन धोखाधड़ी, पहचान की चोरी और व्यक्तिगत जानकारी के दुरुपयोग का जोखिम बढ़ा है। इसलिए नागरिकों को मजबूत पासवर्ड, दो-स्तरीय प्रमाणीकरण और संदिग्ध संदेशों से सावधानी जैसे सामान्य सुरक्षा उपायों की जानकारी होनी चाहिए। बैंक या सरकारी संस्था के नाम पर भेजे गए किसी भी संदिग्ध लिंक पर व्यक्तिगत जानकारी दर्ज करने से पहले उसकी सत्यता की जाँच करना आवश्यक है। डिजिटल साक्षरता का अर्थ केवल मोबाइल चलाना नहीं, बल्कि ऑनलाइन जानकारी का सुरक्षित और विवेकपूर्ण उपयोग करना भी है। विद्यार्थियों को साइबर सुरक्षा, सूचना की विश्वसनीयता और डिजिटल शिष्टाचार के बारे में शिक्षित किया जाना चाहिए। बुजुर्ग तथा तकनीकी रूप से कम परिचित नागरिकों के लिए सहायता केंद्र और सरल सेवाएँ उपयोगी हो सकती हैं। डिजिटल प्रशासन में पारदर्शिता और दक्षता बढ़ाने की संभावना है, लेकिन तकनीकी व्यवस्था के साथ मानवीय सहायता की आवश्यकता भी बनी रहती है। इंटरनेट की सुविधा सभी नागरिकों तक समान रूप से पहुँचाना डिजिटल विभाजन को कम करने के लिए आवश्यक है। बिजली, नेटवर्क, उपकरण और स्थानीय भाषा में सामग्री की उपलब्धता इस दिशा में महत्वपूर्ण है। डिजिटल अर्थव्यवस्था में छोटे व्यवसायों को नए बाजार और ग्राहकों तक पहुँच मिल सकती है। साथ ही, डेटा की गोपनीयता और नागरिक अधिकारों की रक्षा के लिए उचित नियम तथा संस्थागत व्यवस्था आवश्यक है। प्रौद्योगिकी तभी व्यापक सामाजिक लाभ प्रदान कर सकती है जब वह सुरक्षित, सुलभ, पारदर्शी और नागरिकों की वास्तविक आवश्यकताओं के अनुरूप हो।",
"स्वच्छता और सार्वजनिक स्वास्थ्य का आपस में गहरा संबंध है। स्वच्छ वातावरण से अनेक संक्रामक रोगों के प्रसार को कम करने में सहायता मिलती है और नागरिकों के जीवन की गुणवत्ता बेहतर होती है। घर, विद्यालय, बाजार, सड़क, अस्पताल और सार्वजनिक स्थानों की स्वच्छता बनाए रखना केवल प्रशासन की जिम्मेदारी नहीं, बल्कि समाज की सामूहिक जिम्मेदारी है। खुले में कचरा फेंकने से दुर्गंध, कीटों की वृद्धि और जल तथा मिट्टी के प्रदूषण की समस्या उत्पन्न हो सकती है। यदि कचरे का उचित पृथक्करण किया जाए तो जैविक और पुनर्चक्रण योग्य सामग्री को अलग-अलग संसाधित किया जा सकता है। गीले कचरे से खाद तैयार की जा सकती है, जबकि कागज, धातु, काँच और कुछ प्रकार के प्लास्टिक का पुनर्चक्रण संभव है। नगर निकायों को नियमित कचरा संग्रहण, वैज्ञानिक निस्तारण और स्वच्छ जल निकासी की व्यवस्था करनी चाहिए। नागरिकों को भी कचरा निर्धारित स्थान पर डालना और सार्वजनिक स्थलों पर स्वच्छता बनाए रखना चाहिए। विद्यालयों में स्वच्छता संबंधी गतिविधियों के माध्यम से बच्चों में व्यवहारिक आदतें विकसित की जा सकती हैं। स्वच्छ पेयजल की उपलब्धता सार्वजनिक स्वास्थ्य का एक महत्वपूर्ण आधार है। दूषित पानी से विभिन्न जलजनित रोग फैल सकते हैं, इसलिए जल स्रोतों की सुरक्षा और नियमित गुणवत्ता परीक्षण आवश्यक है। शौचालयों की पर्याप्त उपलब्धता और उनका नियमित रखरखाव भी स्वच्छता व्यवस्था का महत्वपूर्ण भाग है। ग्रामीण क्षेत्रों में स्वच्छता के लिए स्थानीय समुदाय की भागीदारी विशेष रूप से उपयोगी हो सकती है। अस्पतालों और स्वास्थ्य केंद्रों में जैव-चिकित्सीय कचरे का निपटान निर्धारित नियमों के अनुसार होना चाहिए, क्योंकि इसके गलत प्रबंधन से संक्रमण का खतरा बढ़ सकता है। स्वच्छता अभियानों की सफलता केवल निर्माण कार्यों पर निर्भर नहीं करती; लोगों के व्यवहार में स्थायी परिवर्तन भी आवश्यक है। पानी की बचत, हाथ धोने की आदत, भोजन को ढककर रखना और आसपास कचरा न जमा होने देना छोटे लेकिन प्रभावी कदम हैं। सार्वजनिक स्वास्थ्य पर होने वाले खर्च को कम करने के लिए रोकथाम और स्वच्छता में निवेश उपयोगी है। स्वच्छ शहर और गाँव पर्यटन, व्यापार तथा सामाजिक जीवन के लिए भी बेहतर वातावरण प्रदान करते हैं। इसलिए स्वच्छता को अभियान के बजाय नियमित नागरिक व्यवहार और प्रशासनिक व्यवस्था का हिस्सा बनाया जाना चाहिए।",
"भारतीय संविधान देश की शासन व्यवस्था का मूल आधार है। संविधान सभा ने लंबे विचार-विमर्श के बाद संविधान को 26 नवंबर 1949 को अंगीकृत किया और 26 जनवरी 1950 को इसे लागू किया गया। इस दिन भारत एक गणराज्य के रूप में स्थापित हुआ। संविधान ने शासन की संस्थाओं, उनके अधिकारों और नागरिकों के मूल अधिकारों तथा कर्तव्यों का विस्तृत ढाँचा निर्धारित किया। प्रस्तावना संविधान के मूल आदर्शों को व्यक्त करती है और न्याय, स्वतंत्रता, समानता तथा बंधुता को राष्ट्रीय जीवन के महत्वपूर्ण मूल्यों के रूप में स्थापित करती है। मौलिक अधिकार नागरिकों को गरिमा और स्वतंत्रता से संबंधित महत्वपूर्ण संरक्षण प्रदान करते हैं। इनमें समानता का अधिकार, स्वतंत्रता का अधिकार, शोषण के विरुद्ध अधिकार, धार्मिक स्वतंत्रता का अधिकार, सांस्कृतिक और शैक्षिक अधिकार तथा संवैधानिक उपचार का अधिकार शामिल हैं। संविधान नागरिकों के लिए कुछ मौलिक कर्तव्यों का भी उल्लेख करता है, जिनमें संविधान, राष्ट्रीय प्रतीकों और पर्यावरण के प्रति सम्मान जैसी जिम्मेदारियाँ शामिल हैं। भारतीय शासन व्यवस्था में संघ और राज्यों के बीच शक्तियों का विभाजन किया गया है। संसद राष्ट्रीय स्तर पर कानून बनाने का कार्य करती है, जबकि राज्य विधानसभाएँ अपने अधिकार क्षेत्र से संबंधित कानून बनाती हैं। न्यायपालिका संविधान की व्याख्या और कानूनों की न्यायिक समीक्षा में महत्वपूर्ण भूमिका निभाती है। स्वतंत्र न्यायपालिका लोकतांत्रिक व्यवस्था में अधिकारों की रक्षा और संस्थागत संतुलन बनाए रखने में सहायक होती है। संविधान में समय के साथ आवश्यक संशोधन भी किए गए हैं, जिससे बदलती सामाजिक और प्रशासनिक परिस्थितियों के अनुसार व्यवस्था में परिवर्तन संभव हुआ है। पंचायती राज और नगर निकायों को संवैधानिक आधार मिलने से स्थानीय स्तर पर लोकतांत्रिक भागीदारी को मजबूत करने का अवसर मिला। संविधान केवल कानूनी दस्तावेज नहीं, बल्कि शासन और नागरिक जीवन के लिए मार्गदर्शक सिद्धांतों का व्यापक आधार है। नागरिकों के लिए संविधान को समझना इसलिए आवश्यक है क्योंकि अधिकारों और कर्तव्यों की जानकारी लोकतांत्रिक भागीदारी को अधिक प्रभावी बनाती है। संवैधानिक संस्थाओं का सम्मान, कानून का पालन और सामाजिक सद्भाव लोकतंत्र की स्थिरता के लिए आवश्यक हैं। संविधान की सफलता उसके शब्दों के साथ-साथ उन मूल्यों को व्यवहार में लागू करने पर निर्भर करती है।",
"जल मानव जीवन, कृषि, उद्योग और पारिस्थितिक संतुलन के लिए अत्यंत आवश्यक प्राकृतिक संसाधन है। पृथ्वी पर जल की मात्रा बहुत अधिक दिखाई देती है, लेकिन पीने और घरेलू उपयोग के लिए उपलब्ध मीठे जल का हिस्सा सीमित है। भारत के अनेक क्षेत्रों में वर्षा का वितरण समान नहीं है। कुछ स्थानों पर भारी वर्षा होती है, जबकि अन्य क्षेत्रों में लंबे समय तक सूखे की स्थिति बनी रह सकती है। भूजल पर अत्यधिक निर्भरता के कारण कई क्षेत्रों में जल स्तर में कमी देखी गई है। कृषि में सिंचाई के लिए बड़ी मात्रा में पानी का उपयोग होता है, इसलिए जल दक्षता बढ़ाना आवश्यक है। ड्रिप और स्प्रिंकलर सिंचाई जैसी तकनीकें कुछ फसलों में पानी की बचत कर सकती हैं। वर्षा जल संचयन शहरी और ग्रामीण दोनों क्षेत्रों में उपयोगी उपाय है। घरों, विद्यालयों और सरकारी भवनों की छतों से वर्षा का पानी एकत्र कर उसे भूजल पुनर्भरण या अन्य उपयुक्त कार्यों में उपयोग किया जा सकता है। तालाब, झील, नदी और आर्द्रभूमि जैसे जल स्रोतों का संरक्षण भी महत्वपूर्ण है। जल निकायों में कचरा और अनुपचारित सीवेज डालने से जल की गुणवत्ता खराब होती है तथा जलीय जीवों और मानव स्वास्थ्य पर प्रतिकूल प्रभाव पड़ सकता है। उद्योगों को अपशिष्ट जल का उपचार करके ही उसे पर्यावरण में छोड़ना चाहिए। शहरों में पाइपलाइन से पानी पहुँचाने के साथ-साथ रिसाव को रोकना भी आवश्यक है, क्योंकि वितरण के दौरान बड़ी मात्रा में पानी नष्ट हो सकता है। नागरिक स्तर पर नल खुला न छोड़ना, रिसाव की मरम्मत कराना और पानी का पुनः उपयोग करना उपयोगी आदतें हैं। विद्यालयों में जल संरक्षण के विषय पर परियोजनाएँ और जागरूकता कार्यक्रम आयोजित किए जा सकते हैं। जल विवादों के समाधान के लिए राज्यों के बीच सहयोग, वैज्ञानिक आँकड़ों और न्यायसंगत नीति की आवश्यकता होती है। जलवायु परिवर्तन के कारण वर्षा के स्वरूप और तापमान में परिवर्तन से जल प्रबंधन की चुनौतियाँ बढ़ सकती हैं। इसलिए जल संरक्षण को केवल संकट के समय की गतिविधि नहीं, बल्कि निरंतर विकास नीति का हिस्सा बनाया जाना चाहिए। सुरक्षित और पर्याप्त जल की उपलब्धता भविष्य की खाद्य सुरक्षा, स्वास्थ्य और आर्थिक स्थिरता से सीधे जुड़ी हुई है।",
"भारत में महिला सशक्तिकरण सामाजिक और आर्थिक विकास का महत्वपूर्ण विषय है। महिलाओं की शिक्षा, स्वास्थ्य, सुरक्षा, रोजगार और राजनीतिक भागीदारी में सुधार से परिवार और समाज दोनों को लाभ मिलता है। ऐतिहासिक रूप से अनेक सामाजिक परिस्थितियों ने महिलाओं की शिक्षा और सार्वजनिक जीवन में भागीदारी को सीमित किया था, लेकिन सामाजिक सुधार आंदोलनों और आधुनिक शिक्षा ने धीरे-धीरे परिवर्तन का मार्ग प्रशस्त किया। आज महिलाएँ विज्ञान, प्रशासन, सेना, खेल, उद्योग, चिकित्सा, शिक्षा, राजनीति और उद्यमिता सहित अनेक क्षेत्रों में योगदान दे रही हैं। फिर भी समान अवसर सुनिश्चित करने के लिए कई स्तरों पर निरंतर प्रयास आवश्यक हैं। बालिकाओं की शिक्षा महिला सशक्तिकरण की आधारभूत आवश्यकता है। गुणवत्तापूर्ण विद्यालय, सुरक्षित परिवहन, छात्रवृत्ति और परिवारों में शिक्षा के प्रति सकारात्मक दृष्टिकोण बालिकाओं की शिक्षा जारी रखने में सहायता कर सकते हैं। कौशल विकास और रोजगार के अवसर महिलाओं को आर्थिक रूप से अधिक स्वतंत्र बना सकते हैं। स्वयं सहायता समूहों ने अनेक ग्रामीण क्षेत्रों में महिलाओं को बचत, ऋण, प्रशिक्षण और छोटे व्यवसायों से जोड़ने में भूमिका निभाई है। कार्यस्थल पर सुरक्षित वातावरण और समान अवसर सुनिश्चित करना आवश्यक है। महिलाओं की राजनीतिक भागीदारी बढ़ाने से स्थानीय और राष्ट्रीय निर्णय प्रक्रिया में विविध अनुभवों को स्थान मिलता है। स्वास्थ्य के क्षेत्र में मातृ स्वास्थ्य, पोषण, प्रजनन स्वास्थ्य और मानसिक कल्याण पर पर्याप्त ध्यान देना आवश्यक है। कानून महिलाओं को विभिन्न प्रकार के शोषण और हिंसा से सुरक्षा प्रदान करते हैं, लेकिन कानूनों के प्रभावी क्रियान्वयन के साथ सामाजिक जागरूकता भी जरूरी है। परिवार में घरेलू कार्य और देखभाल की जिम्मेदारियों का उचित बँटवारा महिलाओं के लिए शिक्षा और रोजगार के अवसर बढ़ा सकता है। मीडिया और शिक्षा संस्थानों को महिलाओं के प्रति सम्मानजनक तथा समान दृष्टिकोण को बढ़ावा देना चाहिए। महिला सशक्तिकरण का अर्थ केवल महिलाओं को सहायता देना नहीं, बल्कि उन्हें निर्णय लेने, संसाधनों तक पहुँच और अवसरों में समान भागीदारी प्रदान करना है। जब समाज की आधी आबादी अपनी क्षमता का पूर्ण उपयोग कर पाती है, तब मानव संसाधन का अधिक प्रभावी विकास संभव होता है। इसलिए महिला सशक्तिकरण को सामाजिक न्याय के साथ-साथ राष्ट्रीय विकास की रणनीति का भी महत्वपूर्ण हिस्सा माना जाना चाहिए।",
"रोजगार और कौशल विकास आधुनिक भारतीय अर्थव्यवस्था की महत्वपूर्ण आवश्यकताएँ हैं। भारत की बड़ी युवा आबादी देश के लिए अवसर भी है और जिम्मेदारी भी। यदि युवाओं को गुणवत्तापूर्ण शिक्षा, उचित प्रशिक्षण और रोजगार के अवसर मिलते हैं, तो वे आर्थिक विकास में महत्वपूर्ण योगदान दे सकते हैं। दूसरी ओर, शिक्षा और रोजगार की आवश्यकताओं के बीच अंतर होने पर डिग्री प्राप्त करने के बावजूद कई युवाओं को उपयुक्त काम पाने में कठिनाई हो सकती है। इसलिए विद्यालय और उच्च शिक्षा संस्थानों में व्यावहारिक तथा कौशल आधारित अध्ययन को बढ़ावा देना आवश्यक है। कंप्यूटर, डेटा विश्लेषण, इलेक्ट्रॉनिक्स, स्वास्थ्य सेवाएँ, निर्माण, कृषि तकनीक, पर्यटन और नवीकरणीय ऊर्जा जैसे अनेक क्षेत्रों में नए कौशल की आवश्यकता बढ़ रही है। व्यावसायिक प्रशिक्षण संस्थानों को उद्योगों की वास्तविक आवश्यकताओं के अनुरूप पाठ्यक्रम विकसित करने चाहिए। प्रशिक्षण में केवल सैद्धांतिक जानकारी नहीं, बल्कि मशीनों, उपकरणों और वास्तविक कार्य परिस्थितियों का अनुभव भी शामिल होना चाहिए। अप्रेंटिसशिप और कार्यस्थल आधारित प्रशिक्षण युवाओं को रोजगार की दुनिया से परिचित कराने में उपयोगी हो सकते हैं। उद्यमिता भी रोजगार का एक महत्वपूर्ण माध्यम बन सकती है। छोटे व्यवसाय और स्टार्टअप नए उत्पाद तथा सेवाएँ विकसित करने के साथ अन्य लोगों के लिए भी रोजगार उत्पन्न कर सकते हैं। इसके लिए वित्तीय सहायता, बाजार की जानकारी, डिजिटल सुविधा और सरल प्रशासनिक प्रक्रियाएँ आवश्यक हैं। ग्रामीण क्षेत्रों में कौशल विकास कार्यक्रमों को स्थानीय आर्थिक गतिविधियों से जोड़ा जाना चाहिए, ताकि प्रशिक्षित युवाओं को अपने क्षेत्र में अवसर मिल सकें। महिलाओं और आर्थिक रूप से कमजोर वर्गों के लिए विशेष प्रशिक्षण तथा सहायता कार्यक्रम सामाजिक समावेशन को बढ़ा सकते हैं। रोजगार की गुणवत्ता भी महत्वपूर्ण है। सुरक्षित कार्यस्थल, उचित वेतन, सामाजिक सुरक्षा और श्रम कानूनों का पालन श्रमिकों के सम्मान और आर्थिक स्थिरता से जुड़ा है। बदलती तकनीक के कारण जीवन में एक बार प्रशिक्षण प्राप्त करना पर्याप्त नहीं रह गया है। निरंतर सीखने और कौशल उन्नयन की आवश्यकता बढ़ रही है। सरकार, उद्योग, शिक्षण संस्थान और नागरिक समाज मिलकर कौशल विकास का मजबूत तंत्र बना सकते हैं। रोजगार योग्य युवाओं की संख्या बढ़ाना केवल बेरोजगारी कम करने का साधन नहीं है; यह उत्पादकता, घरेलू आय, नवाचार और सामाजिक स्थिरता को भी मजबूत करता है।",
"भारत का स्वतंत्रता आंदोलन अनेक विचारधाराओं, संगठनों और जन आंदोलनों से मिलकर बना एक विस्तृत ऐतिहासिक संघर्ष था। 1857 का विद्रोह ब्रिटिश शासन के विरुद्ध एक महत्वपूर्ण प्रारंभिक चुनौती माना जाता है। इसके बाद भारतीय राजनीतिक चेतना धीरे-धीरे संगठित रूप में विकसित हुई। 1885 में भारतीय राष्ट्रीय कांग्रेस की स्थापना ने राजनीतिक मांगों को एक मंच प्रदान किया। प्रारंभिक नेताओं ने संवैधानिक सुधार, प्रशासन में भारतीयों की भागीदारी और अधिकारों के विस्तार पर बल दिया। 1905 में बंगाल विभाजन के विरोध में स्वदेशी और बहिष्कार आंदोलनों को व्यापक समर्थन मिला। आगे चलकर राष्ट्रीय आंदोलन अधिक जन-आधारित हुआ। महात्मा गांधी ने सत्याग्रह और अहिंसक प्रतिरोध को राजनीतिक संघर्ष का महत्वपूर्ण माध्यम बनाया। असहयोग आंदोलन 1920 में प्रारंभ हुआ और इसका उद्देश्य औपनिवेशिक संस्थाओं से सहयोग कम करना था। 1930 में नमक कानून के विरोध में दांडी मार्च ने सविनय अवज्ञा आंदोलन को व्यापक जनसमर्थन दिलाया। 1942 का भारत छोड़ो आंदोलन ब्रिटिश शासन के तत्काल अंत की मांग से जुड़ा था। इन आंदोलनों के साथ-साथ क्रांतिकारी संगठनों और नेताओं ने भी स्वतंत्रता संघर्ष में अलग-अलग तरीकों से योगदान दिया। सुभाष चंद्र बोस और आजाद हिंद फौज राष्ट्रीय आंदोलन के एक महत्वपूर्ण पक्ष का प्रतिनिधित्व करते हैं। महिलाओं ने भी आंदोलनों, जनसभाओं, सामाजिक कार्यों और भूमिगत गतिविधियों में सक्रिय भूमिका निभाई। किसानों, श्रमिकों, विद्यार्थियों और व्यापारियों की भागीदारी ने आंदोलन को व्यापक सामाजिक आधार प्रदान किया। स्वतंत्रता आंदोलन के भीतर राजनीतिक रणनीति, सामाजिक सुधार और आर्थिक व्यवस्था को लेकर विभिन्न मत भी मौजूद थे। 15 अगस्त 1947 को भारत स्वतंत्र हुआ, लेकिन विभाजन के कारण बड़े पैमाने पर विस्थापन और मानवीय पीड़ा हुई। स्वतंत्रता के बाद संविधान निर्माण ने लोकतांत्रिक शासन की दिशा निर्धारित की। स्वतंत्रता आंदोलन का अध्ययन केवल अतीत की घटनाओं को जानने के लिए नहीं, बल्कि नागरिक अधिकारों, राष्ट्रीय एकता और लोकतांत्रिक जिम्मेदारियों को समझने के लिए भी आवश्यक है। इतिहास हमें यह समझने में सहायता करता है कि स्वतंत्रता अनेक लोगों के लंबे संघर्ष, त्याग और राजनीतिक जागरूकता का परिणाम थी।",
"भारतीय रेलवे देश की परिवहन व्यवस्था का एक महत्वपूर्ण हिस्सा है और इसका इतिहास उन्नीसवीं शताब्दी से जुड़ा हुआ है। भारत में पहली यात्री रेल सेवा 1853 में मुंबई और ठाणे के बीच प्रारंभ हुई। समय के साथ रेल नेटवर्क का विस्तार विभिन्न क्षेत्रों तक हुआ और रेलवे ने यात्रियों तथा माल के परिवहन में महत्वपूर्ण भूमिका निभाई। स्वतंत्रता के बाद भारतीय रेलवे का क्रमिक विस्तार और एकीकरण हुआ। आज रेलवे लाखों यात्रियों को प्रतिदिन एक स्थान से दूसरे स्थान तक पहुँचाता है और कृषि उत्पाद, खनिज, ईंधन तथा औद्योगिक वस्तुओं के परिवहन में भी महत्वपूर्ण योगदान देता है। रेल परिवहन सड़क मार्ग की तुलना में बड़े पैमाने पर माल और यात्रियों को अपेक्षाकृत कम ऊर्जा में ले जाने की क्षमता रखता है। देश की आर्थिक गतिविधियों के लिए सुरक्षित और समयबद्ध रेल सेवा आवश्यक है। रेलवे में विद्युतीकरण, आधुनिक सिग्नल प्रणाली, स्वचालित नियंत्रण और बेहतर यात्री सुविधाओं पर लगातार ध्यान दिया जा रहा है। स्टेशनों के आधुनिकीकरण से यात्रियों को स्वच्छ प्रतीक्षालय, बेहतर प्रकाश व्यवस्था, डिजिटल सूचना और अन्य सुविधाएँ उपलब्ध कराई जा सकती हैं। सुरक्षा रेलवे संचालन का सबसे महत्वपूर्ण पक्ष है। पटरियों का नियमित निरीक्षण, सिग्नल व्यवस्था का रखरखाव, कर्मचारियों का प्रशिक्षण और आधुनिक तकनीक का उपयोग दुर्घटनाओं को रोकने में सहायक हो सकता है। रेलवे को पर्यावरण की दृष्टि से भी महत्वपूर्ण माना जाता है क्योंकि विद्युत आधारित रेल परिवहन जीवाश्म ईंधन पर निर्भरता कम करने में सहायता कर सकता है, विशेषकर जब बिजली उत्पादन में स्वच्छ ऊर्जा की हिस्सेदारी बढ़ती है। माल परिवहन की क्षमता बढ़ाने के लिए समर्पित माल गलियारों जैसी परियोजनाएँ उद्योग और व्यापार के लिए उपयोगी हो सकती हैं। रेलवे दूरदराज के क्षेत्रों को बड़े बाजारों और शहरों से जोड़ने में भी योगदान देता है। पर्यटन के विकास में रेल यात्रा की विशेष भूमिका है क्योंकि यह विभिन्न ऐतिहासिक और प्राकृतिक स्थलों तक पहुँच उपलब्ध कराती है। रेलवे केवल परिवहन का साधन नहीं, बल्कि देश की आर्थिक और सामाजिक एकता को मजबूत करने वाला महत्वपूर्ण माध्यम भी है। भविष्य में बेहतर तकनीक, सुरक्षा, समयपालन, स्वच्छता और यात्री सुविधा के माध्यम से इसकी भूमिका और अधिक प्रभावी बनाई जा सकती है।",
"समय प्रबंधन विद्यार्थी और कर्मचारी दोनों के लिए सफलता का एक महत्वपूर्ण आधार है। समय एक ऐसा संसाधन है जिसे संग्रहित करके भविष्य में उपयोग नहीं किया जा सकता। प्रत्येक व्यक्ति को प्रतिदिन 24 घंटे समान रूप से मिलते हैं, लेकिन उनका उपयोग अलग-अलग परिणाम उत्पन्न करता है। प्रतियोगी परीक्षाओं की तैयारी करने वाले विद्यार्थियों के लिए समय प्रबंधन विशेष रूप से आवश्यक है क्योंकि उन्हें सीमित अवधि में अनेक विषयों का अध्ययन, पुनरावृत्ति और अभ्यास करना होता है। एक प्रभावी समय-सारणी बनाने से अध्ययन को व्यवस्थित किया जा सकता है। सबसे पहले महत्वपूर्ण विषयों और कार्यों की पहचान करनी चाहिए तथा उन्हें प्राथमिकता के अनुसार क्रम देना चाहिए। कठिन विषयों का अध्ययन उस समय करना उपयोगी हो सकता है जब एकाग्रता अधिक हो। लंबे अध्ययन सत्र के बीच छोटे विराम लेने से ध्यान बनाए रखने में सहायता मिलती है। मोबाइल फोन और सोशल मीडिया का अनावश्यक उपयोग समय की बड़ी हानि कर सकता है, इसलिए अध्ययन के दौरान डिजिटल व्यवधानों को सीमित करना उचित है। परीक्षा की तैयारी में केवल नया पाठ पढ़ना पर्याप्त नहीं होता; नियमित पुनरावृत्ति और प्रश्नपत्रों का अभ्यास भी आवश्यक है। समयबद्ध अभ्यास से विद्यार्थी परीक्षा के वास्तविक वातावरण के लिए तैयार हो सकता है। यदि किसी प्रश्न पर अत्यधिक समय खर्च हो रहा हो, तो उसे अस्थायी रूप से छोड़कर आगे बढ़ना कई परीक्षाओं में उपयोगी रणनीति हो सकती है। दैनिक लक्ष्य छोटे और स्पष्ट होने चाहिए ताकि प्रगति का आकलन किया जा सके। असफल दिन के कारण पूरी योजना छोड़ देना उचित नहीं है। आवश्यकता के अनुसार समय-सारणी में संशोधन किया जा सकता है। पर्याप्त नींद और विश्राम भी समय प्रबंधन का हिस्सा हैं क्योंकि थका हुआ व्यक्ति लंबे समय तक प्रभावी अध्ययन नहीं कर सकता। भोजन, व्यायाम और परिवार के लिए भी उचित समय निर्धारित करना आवश्यक है। समय प्रबंधन का उद्देश्य प्रत्येक मिनट को काम से भर देना नहीं, बल्कि उपलब्ध समय का विवेकपूर्ण उपयोग करना है। नियमितता किसी भी योजना की सफलता में महत्वपूर्ण भूमिका निभाती है। यदि व्यक्ति अपने लक्ष्य स्पष्ट रखे, प्राथमिकताएँ निर्धारित करे और अनावश्यक गतिविधियों को नियंत्रित करे, तो सीमित समय में भी बेहतर परिणाम प्राप्त किए जा सकते हैं। समय का सम्मान करना वास्तव में अपने अवसरों और भविष्य का सम्मान करना है।"
];

const TypingTest = () => {
    const [lang, setLang] = useState('english');
    const [selectedTime, setSelectedTime] = useState(600); // Default 10 Minutes
    const [textLength, setTextLength] = useState(0);
    const [theme, setTheme] = useState(() => localStorage.getItem('typing-theme') || 'mint');
    const [text, setText] = useState(englishTexts[0]);
    const [input, setInput] = useState('');
    const [timeLeft, setTimeLeft] = useState(600); 
    const [isActive, setIsActive] = useState(false);
    const [wpm, setWpm] = useState(0);
    const [mistakes, setMistakes] = useState(0); 
    const [accuracy, setAccuracy] = useState(100); 
    
    // Auto-scroll के लिए नया Ref
    const textDisplayRef = useRef(null);

    useEffect(() => {
        localStorage.setItem('typing-theme', theme);
    }, [theme]);

    // टाइमर का लॉजिक
    useEffect(() => {
        let interval = null;
        if (isActive && timeLeft > 0) {
            interval = setInterval(() => {
                setTimeLeft(time => time - 1);
            }, 1000);
        } else if (timeLeft === 0 && isActive) {
            clearInterval(interval);
            setIsActive(false);
            calculateAndSaveWPM();
        }
        return () => clearInterval(interval);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isActive, timeLeft]);

    // Auto-scroll का लॉजिक: जब भी input बदलेगा, ये कोड एक्टिव लाइन को फोकस में लाएगा
    useEffect(() => {
        if (textDisplayRef.current) {
            const activeChar = textDisplayRef.current.querySelector('.active-char');
            if (activeChar) {
                // टेक्स्ट को अपने आप ऊपर खिसकाने का फॉर्मूला
                textDisplayRef.current.scrollTop = activeChar.offsetTop - textDisplayRef.current.offsetTop - 35;
            }
        }
    }, [input]);

    const loadNewText = (selectedLang, timeValue = selectedTime, wordLimit = textLength) => {
        const texts = selectedLang === 'english' ? englishTexts : hindiTexts;
        const randomText = texts[Math.floor(Math.random() * texts.length)];
        setText(wordLimit === 0 ? randomText : randomText.split(/\s+/).slice(0, wordLimit).join(' '));
        setInput('');
        setTimeLeft(timeValue);
        setIsActive(false);
        setWpm(0);
        setMistakes(0);
        setAccuracy(100);
        
        // नया टेक्स्ट लोड होने पर स्क्रॉल को वापस ऊपर कर दो
        if (textDisplayRef.current) {
            textDisplayRef.current.scrollTop = 0;
        }
    };

    const handleLangChange = (selectedLang) => {
        setLang(selectedLang);
        loadNewText(selectedLang, selectedTime);
    };

    const handleTimeChange = (seconds) => {
        const newTime = Number(seconds);
        setSelectedTime(newTime);
        loadNewText(lang, newTime);
    };

    const handleLengthChange = (words) => {
        const newLength = Number(words);
        setTextLength(newLength);
        loadNewText(lang, selectedTime, newLength);
    };

    const handleChange = (e) => {
        if (!isActive && timeLeft === selectedTime) {
            setIsActive(true); 
        }
        setInput(e.target.value);
    };

    const handleSubmit = () => {
        setIsActive(false);
        calculateAndSaveWPM();
        setTimeLeft(0); // टाइम को 0 करने से रिज़ल्ट स्क्रीन पर आ जाएगा
    };

    const calculateAndSaveWPM = async () => {
        let errorCount = 0;
        for (let i = 0; i < input.length; i++) {
            if (input[i] !== text[i]) {
                errorCount++;
            }
        }
        setMistakes(errorCount);

        let acc = 100;
        if (input.length > 0) {
            acc = Math.round(((input.length - errorCount) / input.length) * 100);
        }
        setAccuracy(acc);

        const totalWords = input.length / 5; 
        const actualTimeTaken = selectedTime - timeLeft; 
        const timeInMinutes = (actualTimeTaken > 0 ? actualTimeTaken : 1) / 60;
        const finalWpm = Math.round(totalWords / timeInMinutes);
        setWpm(finalWpm);

        const token = localStorage.getItem('token'); 
        if (token) {
            try {
                const decodedToken = JSON.parse(atob(token.split('.')[1]));
                const userId = decodedToken.id || decodedToken._id || decodedToken.userId;

                await fetch('/api/scores/save', {
                    method: 'POST',
                    headers: { 
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${token}` 
                    },
                    body: JSON.stringify({ 
                        user: userId, 
                        wpm: finalWpm, 
                        accuracy: acc, 
                        timeTaken: selectedTime 
                    }) 
                });
            } catch (error) {
                console.error("Error saving score", error);
            }
        }
    };

    const formatTime = (seconds) => {
        const minutes = Math.floor(seconds / 60);
        const remainingSeconds = seconds % 60;
        return `${minutes < 10 ? '0' : ''}${minutes}:${remainingSeconds < 10 ? '0' : ''}${remainingSeconds}`;
    };

    return (
        <main className={`typing-app theme-${theme}`}>
            <header className="typing-header">
                <div className="brand-mark" aria-hidden="true">⌁</div>
                <div>
                    <p className="eyebrow">YOUR DAILY KEYBOARD STUDIO</p>
                    <h1>Find your <span>flow.</span></h1>
                    <p className="header-copy">A little practice goes a long way. Set your pace and get in the zone.</p>
                </div>
                <div className="header-badge"><span className="status-dot" /> READY WHEN YOU ARE</div>
            </header>
            
            <section className="practice-card">
                <div className="section-heading">
                    <div>
                        <p className="eyebrow">MAKE IT YOURS</p>
                        <h2>Set up a session</h2>
                    </div>
                    <button className="refresh-button" onClick={() => loadNewText(lang)} type="button">
                        <span aria-hidden="true">↻</span> New passage
                    </button>
                </div>

                <div className="settings-grid">
                    <fieldset className="setting-group">
                        <legend>Language</legend>
                        <div className="choice-row">
                            <button className={`choice-button ${lang === 'english' ? 'selected' : ''}`} onClick={() => handleLangChange('english')} type="button" aria-pressed={lang === 'english'}>English</button>
                            <button className={`choice-button ${lang === 'hindi' ? 'selected' : ''}`} onClick={() => handleLangChange('hindi')} type="button" aria-pressed={lang === 'hindi'}>Hindi</button>
                        </div>
                    </fieldset>
                    <fieldset className="setting-group">
                        <legend>Time</legend>
                        <div className="choice-row time-choices">
                            {[30, 60, 120, 300, 600, 900].map((seconds) => (
                                <button key={seconds} className={`choice-button ${selectedTime === seconds ? 'selected' : ''}`} onClick={() => handleTimeChange(seconds)} type="button" aria-pressed={selectedTime === seconds}>
                                    {seconds < 60 ? `${seconds}s` : `${seconds / 60}m`}
                                </button>
                            ))}
                        </div>
                    </fieldset>
                    <fieldset className="setting-group">
                        <legend>Passage size</legend>
                        <div className="choice-row">
                            {[['50', 'Quick'], ['100', 'Standard'], ['0', 'Full']].map(([value, label]) => (
                                <button key={value} className={`choice-button ${textLength === Number(value) ? 'selected' : ''}`} onClick={() => handleLengthChange(value)} type="button" aria-pressed={textLength === Number(value)}>{label}</button>
                            ))}
                        </div>
                    </fieldset>
                    <fieldset className="setting-group">
                        <legend>Color mood</legend>
                        <div className="theme-choices" role="group" aria-label="Color mood">
                            {['mint', 'violet', 'sunset', 'ocean'].map((option) => (
                                <button key={option} className={`theme-swatch swatch-${option} ${theme === option ? 'selected' : ''}`} onClick={() => setTheme(option)} type="button" aria-label={`${option} theme`} aria-pressed={theme === option} />
                            ))}
                        </div>
                    </fieldset>
                </div>
            </section>

            <div className="session-status">
                <div><span className="status-label">TIME LEFT</span><strong>{formatTime(timeLeft)}</strong></div>
                <div><span className="status-label">LANGUAGE</span><strong>{lang === 'hindi' ? 'Hindi' : 'English'}</strong></div>
                <div><span className="status-label">TARGET</span><strong>{textLength === 0 ? 'Full passage' : `${textLength} words`}</strong></div>
            </div>
            
            <section className="typing-workspace">
                <div className="workspace-heading"><span>PASSAGE</span><span className="live-indicator"><i /> LIVE PRACTICE</span></div>
                <div
                className="text-display"
                ref={textDisplayRef} // Ref जोड़ा गया
                style={{ 
                    fontFamily: lang === 'hindi' ? 'Mangal, Arial' : 'Courier New, Courier, monospace',
                    maxHeight: '175px',
                    overflow: 'auto',
                    position: 'relative',
                    lineHeight: '1.9',
                    textAlign: 'left',
                    scrollBehavior: 'smooth'
                }}
            >
                {text.split('').map((char, index) => {
                    let color = '#ffffff'; 
                    let isCurrentChar = index === input.length; // यह चेक करता है कि अभी कौन सा अक्षर टाइप करना है

                    if (index < input.length) {
                        color = char === input[index] ? '#6e6e80' : '#ff4c4c'; // सही को ग्रे, गलत को लाल किया (Monkeytype स्टाइल)
                    }
                    
                    return (
                        <span 
                            key={index} 
                            className={isCurrentChar ? 'active-char' : ''} // एक्टिव क्लास दी गई
                            style={{ 
                                color: color, 
                                backgroundColor: color === '#ff4c4c' ? 'rgba(255, 76, 76, 0.2)' : 'transparent',
                                borderRadius: '3px',
                                borderBottom: isCurrentChar ? '3px solid #00ffcc' : 'none', // करंट अक्षर के नीचे एक नीली लाइन (Cursor) दिखेगी
                                transition: 'all 0.1s ease'
                            }}>
                            {char}
                        </span>
                    );
                })}
            </div>
            
            <textarea 
                className="type-box"
                value={input}
                onChange={handleChange}
                disabled={timeLeft === 0}
                placeholder="Start typing here… your timer begins with your first keystroke."
                style={{ fontFamily: lang === 'hindi' ? 'Mangal, Arial' : 'Courier New, Courier, monospace', marginTop: '15px' }}
                aria-label="Type the passage here"
            />
            

            <div className="submit-row">
                <button 
                    className="submit-button"
                    onClick={handleSubmit}
                    disabled={timeLeft === 0 || input.length === 0}
                >
                    Finish session <span aria-hidden="true">→</span>
                </button>
                <span className="keyboard-hint">Your timer starts when you type</span>
            </div>
            </section>

            {timeLeft === 0 && (
                <div className="results-card">
                    <p className="eyebrow">SESSION COMPLETE</p>
                    <h2>Nice work. Keep that momentum.</h2>
                    <div className="results-grid">
                        <div><strong>{wpm}</strong><span>WPM</span></div>
                        <div><strong>{accuracy}%</strong><span>ACCURACY</span></div>
                        <div><strong>{mistakes}</strong><span>MISTAKES</span></div>
                    </div>
                </div>
            )}
        </main>
    );
};

export default TypingTest;